2020-10-22T16:59:25|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:/Users/hgong/PycharmProjects/HexSimInstrument/HexSimApp.py", line 75, in <module>
    app = HexSimApp(sys.argv)
  File "C:/Users/hgong/PycharmProjects/HexSimInstrument/HexSimApp.py", line 18, in __init__
    super().__init__(*kwds)  # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\Users\hgong\AppData\Roaming\Python\Python38\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:/Users/hgong/PycharmProjects/HexSimInstrument/HexSimApp.py", line 39, in setup
    self.add_measurement(HamamatsuMeasurement(self))
  File "C:\Users\hgong\AppData\Roaming\Python\Python38\site-packages\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "C:\Users\hgong\PycharmProjects\HexSimInstrument\CameraMeasurement.py", line 27, in setup
    self.ui = load_qt_ui_file(self.ui_filename)
  File "C:\Users\hgong\AppData\Roaming\Python\Python38\site-packages\ScopeFoundry\helper_funcs.py", line 64, in load_qt_ui_file
    ui = uic.loadUi(ui_filename)
  File "C:\Users\hgong\AppData\Roaming\Python\Python38\site-packages\PyQt5\uic\__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "C:\Users\hgong\AppData\Roaming\Python\Python38\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "C:\Users\hgong\AppData\Roaming\Python\Python38\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
  File "C:\Program Files\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Program Files\Python38\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hgong\\PycharmProjects\\HexSimInstrument\\form.ui'

