2020-10-22T17:02:51|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\hgong\AppData\Roaming\Python\Python38\site-packages\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\hgong\AppData\Roaming\Python\Python38\site-packages\ScopeFoundry\measurement.py", line 179, in _thread_run
    self.run()
  File "C:\Users\hgong\PycharmProjects\HexSimInstrument\CameraMeasurement.py", line 143, in run
    [frame, dims] = self.camera.hamamatsu.getLastFrame()
  File "C:\Users\hgong\PycharmProjects\HexSimInstrument\CameraDevice.py", line 1190, in getLastFrame
    hc_data.copyData(paramlock.buf)
  File "C:\Users\hgong\PycharmProjects\HexSimInstrument\CameraDevice.py", line 309, in copyData
    ctypes.memmove(self.np_array.ctypes.data, address, self.size) #copies self.size bytes from address into self.np_array.ctyps.data
OSError: exception: access violation reading 0x0000000000000000

